name: Docs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
      - name: Convert README.md to README.rst
        run: pandoc README.md -o README.rst
      - name: Commit and push README.rst
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.rst
          git commit -m "Update README.rst" -a || echo "No changes to commit"
          if [[ "${{ github.event_name }}" == "push" ]]; then
            git push origin ${{ github.ref }}
          fi
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme sphinx-autoapi myst-parser
      - name: Sphinx build
        run: |
          sphinx-build -b html docs _build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
